# create your drupal and postgres config here, based off the last assignment
version: '3.1'

services:
  drupal:
    image: drupal:8.2
   
    ports:
      - '8080:80' # expose 80 on host and sent to 80 in container
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-themes:/var/www/html/themes
      # this takes advantage of the feature in Docker that a new anonymous
      # volume (which is what we're creating here) will be initialized with the
      # existing content of the image at the same location
      - drupal-sites:/var/www/html/sites
    restart: always

  drupal_db:
    image: postgres:latest  # this will use latest version of postgres
    restart: always 
    volumes: 
      - drupal-data:/var/lib/postgresql/data
    secrets:
      - psql_password
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/psql-pw

secrets:
  psql_password: 
    file: /run/secrets/psql-pw

